Gemfile.lock
app/models/restaurant.rb
db/migrate/20221121060048_create_restaurants.rb
db/schema.rb
test/models/restaurant_test.rb

Model created. Still need to add validations.

Create restaurant model

---

app/models/booking.rb
app/models/user.rb
db/migrate/20221121063418_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

Booking model complete. No validations yet.

Create booking model

---

app/models/restaurant.rb

Add this after Yumi's pullrequest.

added that restaurant belongs to a user(owner)

---

app/models/user.rb

Method:
user.has_restaurants? => True or False

Added method to check if user has restaurants

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/restaurants_controller.rb
app/policies/restaurant_policy.rb
app/views/pages/home.html.erb
app/views/restaurants/show.html.erb

LD, could you please check it? :)

basic restaurant show and landing page no need to be logged in

---

app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_show.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/restaurants/show.html.erb

basic css for show and landing on mobile grid

---

db/seeds.rb

- Fixed bookings-seeds so it works for everyone and after every seed, without configuration.
- Refactored entire seed-file.

seeds fix, update and cleanup

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_show.scss
app/views/pages/home.html.erb
app/views/restaurants/_card.html.erb
app/views/restaurants/_carousel.html.erb
app/views/restaurants/_list.html.erb
app/views/restaurants/index.html.erb
app/views/restaurants/show.html.erb

Styling grids

---

app/models/restaurant.rb
db/seeds.rb

- Added categories in seeds:
categories = ["All you can eat", "All you can drink", "Japanese, Kaiseki, Washoku", "Sushi", "Soba", "Tempura", "Yakiniku", "Steak, Teppanyaki", "Yakitori", "French", "Italian, Trattoria", "Western Cousine", "Chinese", "Bar", "Pub", "Izakaya"]

Seed restaurant categories

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_show.scss
app/views/restaurants/_card.html.erb
app/views/restaurants/show.html.erb

links to bookings

---

app/controllers/bookings_controller.rb
app/controllers/restaurants_controller.rb
app/policies/booking_policy.rb
app/views/bookings/index.html.erb
app/views/restaurants/_card.html.erb
app/views/restaurants/_form.html.erb
config/routes.rb

Merged master, fixed conflicts and re-doing pull request.

Send booking request

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/bookings_controller.rb
app/views/restaurants/_card.html.erb
app/views/restaurants/_form.html.erb
app/views/restaurants/index.html.erb
app/views/shared/_navbar.html.erb

search dropdown into the navbar

search in navbar

---

app/views/restaurants/_card.html.erb
app/views/restaurants/_carousel.html.erb
db/seeds.rb

- Each restaurant x2 Images
- Each card showing the first image
- Each show-page carousel switching between the two images.

Restaurants images seed update

---

app/controllers/bookings_controller.rb
app/controllers/owner/bookings_controller.rb

added tags into owners/bookings

---

app/controllers/restaurants_controller.rb
app/models/restaurant.rb
db/migrate/20221124025328_add_description_to_restaurants.rb
db/schema.rb
db/seeds.rb

- Adds column "description" for restaurants.
- Added descriptions in seeds generation
- Added validations for description
- Added description in strong params for restaurants controller

Add description to restaurants

---

app/views/restaurants/_card.html.erb
app/views/restaurants/_carousel.html.erb

Carousels work on both the index and the show page. We may need to change the amount of pictures in the carousel partial if we want more than two photos

Added carousels to the index

---

app/assets/stylesheets/pages/_show.scss
app/controllers/bookings_controller.rb
app/controllers/pages_controller.rb
app/controllers/restaurants_controller.rb
app/views/layouts/application.html.erb
app/views/restaurants/_card.html.erb
app/views/restaurants/_form.html.erb
app/views/restaurants/show.html.erb
app/views/shared/_navbar.html.erb

Search session navbar

---

app/views/bookings/index.html.erb
app/views/layouts/application.html.erb
app/views/owner/bookings/index.html.erb
app/views/restaurants/index.html.erb
app/views/restaurants/show.html.erb
package.json
yarn.lock

fixing login navbar split in poages

---

app/models/user.rb
app/views/restaurants/index.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

- Owner drop down link to my restaurants
- Seeds cleaned up (-200 lines)
- Removed duplicate navbar

Seed fix new

---

app/assets/stylesheets/pages/_home.scss

Input corrected, thank you, Yumi!!! :)

input fixed for only landing

---

app/assets/stylesheets/pages/_home.scss

nested form style in home

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

landing nested nested

---

app/assets/stylesheets/components/_navbar.scss

Fixed navbar CSS margins. Looks good now.

---

db/seeds.rb

- Removed random restaurants
- Added so we have 3 demo restaurants, all in Shibuya

Seeds new update

---

app/assets/stylesheets/components/_map.scss
app/views/restaurants/_info_window.html.erb

maps popout

---

app/assets/stylesheets/pages/_show.scss
app/views/restaurants/show.html.erb
db/seeds.rb

Reservation confirmed message dessign and map

---

public/404.html
public/500.html

rename of classes for errors messages

---

app/assets/stylesheets/pages/_home.scss

size of dropdown

---

app/assets/stylesheets/components/_result_message.scss
app/views/restaurants/index.html.erb

Font 12px and condition for nill or "1" to show in results.

adjust to results sentence

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card_product.scss
app/assets/stylesheets/components/_charts.scss
app/views/layouts/application.html.erb
app/views/owner/bookings/_card_product.html.erb
app/views/owner/bookings/_charts.html.erb
app/views/owner/bookings/index.html.erb

Owners page 2

---

app/assets/stylesheets/components/_map_modal.scss
app/assets/stylesheets/components/_request_icon.scss
app/javascript/controllers/modal_controller.js
app/views/restaurants/_map_modal.html.erb
app/views/restaurants/index.html.erb
app/views/shared/_navbar.html.erb

Map styling and responsiveness added. Also fixed an issue with the carousel items covering the food icon (shopping cart) by moving the cart up a layer.

Map styling

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card_product.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_owner_navbar.scss
app/views/owner/bookings/_card_product.html.erb
app/views/owner/bookings/_charts.html.erb
app/views/owner/bookings/_owner_navbar.html.erb
app/views/owner/bookings/index.html.erb

Navbar styling for owners-page.

Owners nav bar

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_show.scss
app/views/restaurants/_card.html.erb
app/views/restaurants/show.html.erb

Confirmation show and index page

Reject gray

---

app/assets/stylesheets/components/_card_product.scss
app/javascript/controllers/booking_subscription_controller.js
app/views/bookings/_restaurant_rejected.html.erb

grayscale to the rejected cards

grayscale rejected card in bookings

---

app/assets/stylesheets/components/_index.scss
app/views/bookings/index.html.erb

minor fixing h5

---

app/views/bookings/_card_product.html.erb
app/views/owner/bookings/_card_product.html.erb

fixed an issue with cards showing km away without a distance

km away will now only show if the user has a current location

---

app/views/pages/home.html.erb

last minute reservations
